<a href="https://colab.research.google.com/github/pauarmentaa/Prueba/blob/main/1_Extracci%C3%B3n_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Cargar archivo csv desde equipo
from google.colab import files
files.upload()

CARGA DE ARCHIVO .CSV

In [ ]:
#Convertir en dataframe
#df= pd.read_csv("file.csv")
#df

CARGA DE ARCHIVO XLSX

In [3]:
#Carga desde un archivo .xlsx sin indice
df= pd.read_excel('Antigüedad de saldos 17.03.2023.xlsx')
#df

In [4]:
#Verificamos información del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   No. CLIENTE        164 non-null    object
 1   NOMBRE             164 non-null    object
 2   FACTURA            164 non-null    object
 3   FECHA_FACTURA      164 non-null    datetime64[ns]
 4   FECHA_VENCIMIENTO  164 non-null    datetime64[ns]
 5   MONTO ADEUDADO     164 non-null    float64
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 7.8+ KB

In [5]:
#Imprimo los primeros 5 registro del dataframe
df.head()

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
4,4712,HELVEX,F40173,2023-02-17,2023-04-03,50639.80

**FILTROS BASICOS PARA VARIABLES CUALITATIVAS**

In [13]:
#Filtro por objeto 
filtro1=df[df["NOMBRE"] == "INDUSTRIAS LANCERMEX"]
filtro1

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
12,3930,INDUSTRIAS LANCERMEX,F40114,2023-02-09,2023-03-11,35143.82

In [14]:
#Filtro por filas
filtro2= df.iloc[100:150,: ]           #Filas consecutivas
#filtro2=df.iloc[ [8, 24, 100] , : ]  #Filas no consecutivas 
filtro2

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
100,3926,PRODUCTOS PENNSYLVANIA,F40357,2023-03-14,2023-04-13,2756.16
101,5926,PÚBLICO EN GENERAL,F40362,2023-03-14,2023-03-14,2694.95
102,4802,RAUL SERVIN AGUILLON,F40372,2023-03-15,2023-03-15,2526.48
103,6569,BLANCA ROCIO GARCIA MORALES,F40338,2023-03-10,2023-03-10,2334.50
104,3916,VINILOS,F40375,2023-03-16,2023-03-31,2256.14
105,8432,ALIMENTOS GOURMET DEL BAJIO,F35926,2021-08-23,2021-08-23,2094.96
106,466,DEACERO,F38995,2022-09-06,2022-11-05,2088.00
107,6326,JORGE HERBERT PEREZ,F35927,2021-08-23,2021-08-23,2000.00
108,6885,CAPTIVE SPORT,F40337,2023-03-10,2023-03-10,1949.38
109,2768,CEREALES Y PASTAS,F40216,2023-02-22,2023-03-24,1925.60
110,42,ELASTOMEROS DE QUERETARO,F40343,2023-03-13,2023-04-12,1827.00
111,8861,ABASTECEDORA GOURMET,F40342,2023-03-13,2023-03-13,1740.79
112,161,LBQ FOUNDRY,F40092,2023-02-07,2023-03-09,1740.00
113,2216,FRESCOPACK,F40355,2023-03-14,2023-03-14,1682.00
114,8859,MARI CARMEN ALONZO MORA,F40247,2023-02-27,2023-02-27,1682.00
115,3512,HOSPITAL SAN JOSE DE CELAYA,F35700,2021-07-29,2021-08-28,1647.20
116,6928,SUAJADOS ESPECIALES Y MAQUILA DE EMPAQUE INDUS...,F40332,2023-03-10,2023-03-10,1608.15
117,8132,CARLOS ALBERTO HERNANDEZ MIRANDA,NV00749,2023-01-16,2023-01-16,1479.00
118,6053,DEX STAR,F40333,2023-03-10,2023-03-10,1401.57
119,3916,VINILOS,F40378,2023-03-16,2023-03-31,1390.72
120,3836,EMZ HANAUER DE MEXICO,F40103,2023-02-08,2023-02-08,1264.40
121,2527,OSANIA CLEANING & SANITIZING,F39257,2022-10-06,2022-11-05,1229.95
122,3228,KERN LIEBERS MEXICO,F40144,2023-02-14,2023-02-14,1204.08
123,5598,MECAPRIM SERVICIOS INDUSTRIALES,F40368,2023-03-15,2023-03-15,1179.95
124,8378,JAKBA-SEE,F40380,2023-03-16,2023-03-16,1169.28
125,5439,MULTI EQUIPOS AUTOMOTRICES VIZU,F40060,2023-01-31,2023-01-31,1095.85
126,2704,GRUPO ROCE INDUSTRIAL Y COMERCIAL,F40062,2023-01-31,2023-01-31,1068.28
127,6746,JOSE ALEJANDRO DIAZ NIETO,F40339,2023-03-13,2023-03-13,1015.00
128,2704,GRUPO ROCE INDUSTRIAL Y COMERCIAL,F40077,2023-02-02,2023-02-02,1000.00
129,5926,PÚBLICO EN GENERAL,F36340,2021-10-05,2021-10-05,1000.00
130,5926,PÚBLICO EN GENERAL,F37204,2022-01-27,2022-01-27,1000.00
131,5926,PÚBLICO EN GENERAL,NV00356,2021-08-16,2021-08-16,815.00
132,1284,TERMOFORMADOS,F40349,2023-03-14,2023-04-13,799.24
133,2549,MARATHON SYSTEMS CONTROL,F39912,2023-01-12,2023-02-11,765.60
134,8434,FRANCISCO JAVIER MEDINA SANCHEZ,F39426,2022-10-27,2022-10-27,763.04
135,8872,GABRIELA GARCIA SANCHEZ,F40360,2023-03-14,2023-03-14,754.00
136,5598,MECAPRIM SERVICIOS INDUSTRIALES,F40369,2023-03-15,2023-03-15,742.40
137,6746,JOSE ALEJANDRO DIAZ NIETO,F40336,2023-03-10,2023-03-10,730.01
138,8545,JV AGRO,F40373,2023-03-15,2023-03-15,704.41
139,8228,UCH COMERCIAL,F40365,2023-03-14,2023-03-14,702.96
140,O,POLIETILENOS Y PRODUCTOS DE QUERETARO,F40374,2023-03-16,2023-03-16,658.60
141,5926,PÚBLICO EN GENERAL,NV00351,2021-08-06,2021-08-06,591.60
142,8564,DISTRIBUIDORA LIVERPOOL,F40348,2023-03-13,2023-03-13,568.40
143,357,TRATAMIENTOS TERMICOS DE QUERETARO,F39931,2023-01-17,2023-02-01,555.19
144,5926,PÚBLICO EN GENERAL,F36620,2021-11-09,2021-11-09,500.00
145,6885,CAPTIVE SPORT,F36062,2021-09-06,2021-09-06,500.00
146,7059,HEVACSA TERMOENCOGIBLES,F40311,2023-03-07,2023-03-07,487.20
147,8697,ELECTRO FERRETERA REAL,F40314,2023-03-08,2023-03-08,487.20
148,8243,SCIMPLA,F38125,2022-05-10,2022-05-10,420.00
149,8826,ANA KARLA ROSALES VAZQUEZ,F40097,2023-02-07,2023-02-07,406.00

In [18]:
#Filtro por columnas
#filtro3=df.iloc[ : , 1:3]       #Columnas consecutivas 
filtro3=df.iloc[ 1:10 , [1,5]]  #Columnas no consecutivas 
filtro3

                                         NOMBRE  MONTO ADEUDADO
1                          DONGA HWASUNG MEXICO        97485.94
2  PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO        64916.21
3                          INDUSTRIAS LANCERMEX        52715.74
4                                        HELVEX        50639.80
5                AUTOLIV STEERING WHEELS MEXICO        49416.00
6                AUTOLIV STEERING WHEELS MEXICO        49416.00
7                                      BUSSMANN        48882.12
8                         CLAVOS NACIONALES C.N        45216.34
9                         CLAVOS NACIONALES C.N        45216.34

In [ ]:
#Filtro de filas vs columnas 
#Paso 1: Leemos el contenido del archivo
from google.colab import files
uploaded=files.upload()

In [19]:
df1= pd.read_excel('Antigüedad de saldos 17.03.2023.xlsx', index_col=1)
df1

,No. CLIENTE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
NOMBRE,,,,,
DONGA HWASUNG MEXICO,6401,F40238,2023-02-24,2023-03-26,97485.94
DONGA HWASUNG MEXICO,6401,F40353,2023-03-14,2023-04-13,97485.94
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,4598,F40352,2023-03-14,2023-04-13,64916.21
INDUSTRIAS LANCERMEX,3930,F40217,2023-02-23,2023-03-25,52715.74
HELVEX,4712,F40173,2023-02-17,2023-04-03,50639.80
...,...,...,...,...,...
CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADOS DEL INSTITUTO POLITECNICO NACIONAL,856,F40055,2023-01-31,2023-01-31,56.00
PÚBLICO EN GENERAL,5926,NV00777,2023-03-07,2023-03-07,45.00
PÚBLICO EN GENERAL,5926,NV00778,2023-03-09,2023-03-09,40.00
PÚBLICO EN GENERAL,5926,NV00779,2023-03-09,2023-03-09,24.01
FISHERS QUERETARO,8429,F38248,2022-05-27,2022-05-27,19.94

In [20]:
#Paso 2: Aplicamos Filtro de filas vs columnas 
filtro4=df1.loc[["HELVEX","DONGA HWASUNG MEXICO"], ["MONTO ADEUDADO"]]
filtro4

                      MONTO ADEUDADO
NOMBRE
HELVEX                      50639.80
DONGA HWASUNG MEXICO        97485.94
DONGA HWASUNG MEXICO        97485.94
DONGA HWASUNG MEXICO        10759.00
DONGA HWASUNG MEXICO         9396.00

In [21]:
#Filtro por cabecera
filtro5=df.head(10)
filtro5

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
4,4712,HELVEX,F40173,2023-02-17,2023-04-03,50639.80
5,1429,AUTOLIV STEERING WHEELS MEXICO,F39979,2023-01-24,2023-03-25,49416.00
6,1429,AUTOLIV STEERING WHEELS MEXICO,F40319,2023-03-08,2023-05-07,49416.00
7,5039,BUSSMANN,F40082,2023-02-04,2023-02-04,48882.12
8,644,CLAVOS NACIONALES C.N,F40340,2023-03-13,2023-05-12,45216.34
9,644,CLAVOS NACIONALES C.N,F40351,2023-03-14,2023-05-13,45216.34

**FILTROS BASICOS PARA VARIABLES CUANTITATIVAS**

In [22]:
#Filtro por comparacion
filtro6=df[df["MONTO ADEUDADO"] > 70000]
filtro6

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94

**FILTROS BASICOS CON CONETORES LOGICOS**

In [23]:
#Filtro Y
filtro7=df[(df["MONTO ADEUDADO"] < 6000) & (df["FECHA_FACTURA"] == "2023-03-14")]
filtro7

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
85,409,CONSTRUCCIONES ELECTROMECANICAS Y SERVICIOS IN...,F40359,2023-03-14,2023-03-14,4292.00
96,3926,PRODUCTOS PENNSYLVANIA,F40358,2023-03-14,2023-04-13,3368.64
100,3926,PRODUCTOS PENNSYLVANIA,F40357,2023-03-14,2023-04-13,2756.16
101,5926,PÚBLICO EN GENERAL,F40362,2023-03-14,2023-03-14,2694.95
113,2216,FRESCOPACK,F40355,2023-03-14,2023-03-14,1682.00
132,1284,TERMOFORMADOS,F40349,2023-03-14,2023-04-13,799.24
135,8872,GABRIELA GARCIA SANCHEZ,F40360,2023-03-14,2023-03-14,754.00
139,8228,UCH COMERCIAL,F40365,2023-03-14,2023-03-14,702.96

In [25]:
#Filtro o (una u otra)
filtro8=df[(df["MONTO ADEUDADO"] < 6000) | (df["FECHA_FACTURA"] == "2023-03-14")]
filtro8

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
9,644,CLAVOS NACIONALES C.N,F40351,2023-03-14,2023-05-13,45216.34
10,3937,RICHALUM,F40361,2023-03-14,2023-03-14,42880.05
36,417,COVEMEX,F40354,2023-03-14,2023-03-29,15843.28
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

In [26]:
#Filtro not
filtro9=df[~(df["MONTO ADEUDADO"] >= 6000) & ~(df["FECHA_FACTURA"] == "2023-03-14")]
filtro9

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
70,1852,ITW POLY MEX,F40201,2023-02-22,2023-03-24,5967.85
71,8316,ANA BARBARA CRUZ PALACIOS,F40379,2023-03-16,2023-03-31,5827.84
72,8787,ARMANDO VIDAURRETA PEÑA,F39769,2022-12-14,2022-12-14,5800.00
73,2768,CEREALES Y PASTAS,F40215,2023-02-22,2023-03-24,5660.80
74,1831,DISTRIBUCIONES Y REPRESENTACIONES CALORA,F40316,2023-03-08,2023-04-22,5502.81
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

In [27]:
#Convertir archivo filtrado a CSV
filtro9.to_csv("Entregable1.csv")

In [28]:
#descardar archivo filtrado en csv
from google.colab import files 
  
  
files.download("Entregable1.csv")